apiVersion: v1
kind: Service
metadata:
  name: kube-sec-be
  namespace: kube-security
  labels:
    app.kubernetes.io/name: kube-sec
spec:
  type: ClusterIP
  ports:
  - port: 50000
    targetPort: 50000
  selector:
    app.kubernetes.io/name: kube-sec