---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-security
---
apiVersion: v1
kind: Service
metadata:
  name: kube-sec
  namespace: kube-security
  labels:
    app.kubernetes.io/name: kube-sec
spec:
  type: ClusterIP
  ports:
  - port: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: kube-sec-be
  namespace: kube-security
  labels:
    app.kubernetes.io/name: kube-sec
spec:
  containers:
  - name: kubernetes-security
    image: snowline2015/kubernetes-security:latest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-sec
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-sec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-sec
subjects:
- kind: ServiceAccount
  name: kube-sec
  namespace: kube-security
    