apiVersion: v1
kind: Namespace
metadata:
  name: kube-security
---



apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-sec
  namespace: kube-security
  labels:
    
---



apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-sec
  namespace: kube-security
rules:
- apiGroups: ["", "metrics.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---



apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-sec
  namespace: kube-security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-sec
subjects:
- kind: ServiceAccount
  name: kube-sec
  namespace: kube-security 
---



apiVersion: v1
kind: Service
metadata:
  name: kube-sec-be
  namespace: kube-security
  labels:
    app.kubernetes.io/name: kube-sec
spec:
  type: ClusterIP
  ports:
  - port: 50000
    targetPort: 50000
  selector:
    app.kubernetes.io/name: kube-sec
---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-sec-be
  namespace: kube-security
  labels:
    app.kubernetes.io/name: kube-sec
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-sec
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-sec
    spec:
      serviceAccountName: kube-sec
      containers:
      - name: kubernetes-security
        image: snowline2015/kubernetes-security:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50000
---