---
apiVersion: v1
kind: Service
metadata:
  name: yorha
  labels:
    app.kubernetes.io/name: yorha
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    org: nier
    class: yorha
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yorha
  labels:
    app.kubernetes.io/name: yorha
spec:
  replicas: 2
  selector:
    matchLabels:
      org: nier
      class: yorha
  template:
    metadata:
      labels:
        org: nier
        class: yorha
        app.kubernetes.io/name: yorha
    spec:
      containers:
      - name: nginx
        image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: 2b
  labels:
    org: nier
    class: battle
    app.kubernetes.io/name: 2b
spec:
  containers:
  - name: nginx
    image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: a2
  labels:
    org: resistance
    class: attack
    app.kubernetes.io/name: a2
spec:
  containers:
  - name: nginx
    image: nginx:latest