apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-sec-be
  namespace: kube-security
  labels:
    app.kubernetes.io/name: kube-sec
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-sec
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-sec
    spec:
      serviceAccountName: kube-sec
      containers:
      - name: kubernetes-security
        image: snowline2015/kubernetes-security:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50000