---
apiVersion: v1
kind: Namespace
metadata:
  name: bunker
---
apiVersion: v1
kind: Service
metadata:
  name: nier
  namespace: bunker
  labels:
    app.kubernetes.io/name: nier
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    org: yorha
    class: nier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nier
  namespace: bunker
  labels:
    app.kubernetes.io/name: nier
spec:
  replicas: 2
  selector:
    matchLabels:
      org: yorha
      class: nier
  template:
    metadata:
      labels:
        org: yorha
        class: nier
        app.kubernetes.io/name: nier
    spec:
      containers:
      - name: nginx
        image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: 2b
  namespace: bunker
  labels:
    org: yorha
    class: battle
    app.kubernetes.io/name: 2b
spec:
  containers:
  - name: nginx
    image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: a2
  namespace: bunker
  labels:
    org: resistance
    class: attack
    app.kubernetes.io/name: a2
spec:
  containers:
  - name: nginx
    image: nginx:latest